format_version: 2
environments:
  ci:
    pipelines:
      - "ui"
      
pipelines:
  "ui":
    group: team1
    materials:
      ui:
        git: "git@github.com:balabarath/cricket-scorer-ui.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    yarn run test_with_coverage
      - build:
          jobs:
            build:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    REACT_APP_API_URL="http://18.207.74.29:9090" yarn run build              

      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    sh ./buildAndDeploy/deploy.sh team1
